apiVersion: v1
description: Provides easy monitoring definitions for Kubernetes services, and deployment
  and management of Prometheus instances.
engine: gotpl
maintainers:
- email: mgoodness@gmail.com
  name: Michael Goodness
- email: gianrubio@gmail.com
  name: Giancarlo Rubio
name: prometheus-operator
sources:
- https://github.com/coreos/prometheus-operator
version: 0.0.15
