apiVersion: v1
description: Prometheus instance created by the CoreOS Prometheus Operator
engine: gotpl
maintainers:
- email: mgoodness@gmail.com
  name: Giancarlo Rubio
name: prometheus
sources:
- https://github.com/coreos/prometheus-operator
version: 0.0.25
